# Generated by Django 2.2 on 2020-10-31 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('details', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, null=True)),
                ('email', models.CharField(max_length=300, null=True)),
                ('phone_number', models.CharField(max_length=300, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('clothes_number', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('organizer_name', models.CharField(max_length=300, null=True)),
                ('details', models.TextField(max_length=300, null=True)),
                ('phone_number', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_front', models.ImageField(blank=True, upload_to='')),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('category', models.CharField(max_length=300, null=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('author', models.CharField(max_length=300, null=True)),
                ('details', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage', models.ImageField(blank=True, upload_to='')),
                ('img1', models.ImageField(blank=True, upload_to='')),
                ('img2', models.ImageField(blank=True, upload_to='')),
                ('img3', models.ImageField(blank=True, upload_to='')),
                ('price', models.FloatField()),
                ('studio_name', models.CharField(max_length=300, null=True)),
                ('size', models.CharField(max_length=300, null=True)),
                ('gender', models.CharField(max_length=300, null=True)),
                ('category', models.CharField(max_length=300, null=True)),
                ('rent_price', models.FloatField(null=True)),
                ('count', models.IntegerField(default=0)),
                ('rented', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
