# Generated by Django 2.2 on 2020-10-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201101_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='details',
        ),
        migrations.AddField(
            model_name='events',
            name='bio',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
