# Generated by Django 2.2 on 2020-10-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201101_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='venue',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
